### ISSUE TITLE
CSS is now broken

### ISSUE THREAD

**Issue by mistermantas** [Sirius207/Stylish-Dark-Gray-Dropbox-Paper#1]
It doesn’t work for the homepage at all anymore and, at least to me, in the editor [the border colors](https://gyazo.com/6462027ce8d25a485e5d8eaaec056152) are a bit too bright for my tastes.

**Comment by mistermantas** [comment]
@Sirius207, are you still even using Paper? Would you look into fixing this?

**Comment by mistermantas** [comment]
Nevermind, this is a dead project.

**Comment by Sirius207** [comment]
Hello @mistermantas , I'm sorry for not checking this repo (& notifications) for a long while.
I don`t use this style any more. Instead, I use the [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=zh-TW) to satisfy the original requirement. 

Now I update this repo to change the background color of editor to Black again.
On the other hand, which border color do you think is too bright?

this one?
![image](https://user-images.githubusercontent.com/7900936/27003059-74636a82-4e22-11e7-9bcc-0125e8831c4a.png)

Thanks for your kind reminder.
